### ISSUE TITLE
Error reading lists with C-3P0 (resistance)

### ISSUE THREAD

**Issue by stickus** [jychuah/XwingTabled#8]
I think your may have the name wrong for 3P0, as it can't read any XWS file with resistance 3P0 in it.

**Comment by jychuah** [comment]
Can you paste your XWS here? What source is it from?

**Comment by jychuah** [comment]
I've made a shim for YASB 2.0. You can do a hard reload on the page and you should be able to import it now. Please let me know if the error still persists.

**Comment by stickus** [comment]
Jeez I was just about to load the XWS. Couldn't use the version from YASB or Launch Bay Next. Here's the XWS in any case:

{"name":"00 - Vennie, Jess, Talli","faction":"resistance","format":"Hyperspace","favourite":true,"pilots":[{"ship":"mg100starfortress","upgrades":{"device":["seismiccharges","proximitymines"],"gunner":["veteranturretgunner"],"sensor":["trajectorysimulator"],"crew":["c3po-crew"],"modification":["hullupgrade"]},"id":"vennie","points":96},{"ship":"t70xwing","upgrades":{"astromech":["bbastromech"],"tech":["advancedoptics"],"configuration":["integratedsfoils"]},"id":"jessikapava","points":59},{"ship":"rz2awing","upgrades":{"talent":["predator","crackshot"],"tech":["patternanalyzer"]},"id":"tallissanlintra","points":43}],"version":"2.20.54","points":198}

**Comment by stickus** [comment]
That was the one from Launch Bay Next. This one is from YASB;

{"description":"","faction":"resistance","name":"00 - Vennie, Jess, Talli","pilots":[{"id":"vennie","name":"vennie","points":96,"ship":"mg100starfortress","upgrades":{"sensor":["trajectorysimulator"],"crew":["c3po-crew"],"gunner":["veteranturretgunner"],"device":["seismiccharges","proximitymines"],"modification":["hullupgrade"]}},{"id":"jessikapava","name":"jessikapava","points":59,"ship":"t70xwing","upgrades":{"astromech":["bbastromech"],"configuration":["integratedsfoils"],"tech":["advancedoptics"]}},{"id":"tallissanlintra","name":"tallissanlintra","points":43,"ship":"rz2awing","upgrades":{"talent":["predator","crackshot"],"tech":["patternanalyzer"]}}],"points":198,"vendor":{"yasb":{"builder":"Yet Another Squad Builder 2.0","builder_url":"https://raithos.github.io/","link":"https://raithos.github.io/?f=Resistance&d=v5!s!294:114,-1,191,90,-1,71,70,164:;296:196,-1,175,186,-1,-1:;240:127,116,-1,206:&sn=00%20-%20Vennie%2C%20Jess%2C%20Talli&obs="}},"version":"2.0.0"}

**Comment by jychuah** [comment]
Fixed! c3poresistance was part of the issue - also I had to patch Initiative based point costs. Please reload the page. Also, use the "nuke data" option in the action button on the left.
